liqd/a4-opin

euth_wagtail/settings/base.py
euth_wagtail/templates/base.html
euth_wagtail/templates/tags/top_menu.html
home/templatetags/base_tags.py

this enables that the menu links are created from the pages that have 'show in menu' checkbox checked

2016 01 mn add generic menu

---

euth_wagtail/static/scss/components/_info-block.scss
euth_wagtail/static/scss/components/_video-block.scss
euth_wagtail/static/scss/core/_bootstrap-variables.scss
euth_wagtail/static/scss/core/_buttons.scss
euth_wagtail/static/scss/core/_containers.scss
home/blocks.py
home/templates/home/blocks/info_block.html

Fixed the highlighting options. Added a 'boxed' option (see homepage design "e-participation"

Fixed highlight options

---

home/templatetags/url_translations.py

fix urls translations

---

euth_wagtail/static/scss/core/_buttons.scss
euth_wagtail/static/scss/core/_mixins.scss
euth_wagtail/templates/base.html
euth_wagtail/templates/includes/feedback_button.html

Added feedback button

---

euth_wagtail/settings/test.py
pytest.ini

Revert "Disable all wagtail apps during pytest testing"

---

euth/user_management/templates/emails/email_base.html
euth/user_management/templates/emails/register.en.html
euth/user_management/templates/emails/register.en.subject
euth/user_management/templates/emails/reset.en.html
tests/user_management/test_views.py

@slomo I suggest to just merge, then people can test with heroku and different clients

add some more styling to emails

---

.gitignore
.travis.yml
README.md
comments_api/static/comments_api/react_comments.js
comments_api/templates/comments_api/react_comments.html
euth_wagtail/settings/base.py
euth_wagtail/static/js/app.js
euth_wagtail/static/scss/core/_bootstrap.scss
euth_wagtail/templates/base.html
package.json
projects/templates/projects/organisation_page.html
projects/templates/projects/organisations_page.html
projects/templates/projects/projects_page.html
requirements.txt
webpack.config.js

Open questions:
- ~~should salvatore also be merged into the bundle~~ (not now)
- ~~should scss also be build with webpack~~ (not now compressor works)

Change js build from bower to webpack

---

euth/comments/static/comments/react_comments.js

fixes https://github.com/liqd/euth_wagtail/issues/80

dont show answer button near deleted comment

---

euth/user_management/templates/emails/email_base.html

Can you test this @rittermo , @MagdaN will he be able to test it right away once merged ?

Fix image alignment fixes #82

---

euth/organisations/templates/euth_organisations/organisation_detail.html
euth_wagtail/settings/dev.py
euth_wagtail/static/scss/components/_accordion-block.scss
euth_wagtail/static/scss/components/_org-page.scss
euth_wagtail/static/scss/core/_buttons.scss
requirements.txt

Some styling of the org page, not much else to do until projects and processes are listed

2016 06 cc orgs page style

---

home/templatetags/url_translations.py
projects/templates/projects/organisation_page.html

fixes https://github.com/liqd/euth_wagtail/issues/99

2016 07 mn translations

---

euth/comments/serializers.py
euth/comments/static/comments/react_comments.js
euth/comments/templates/comments/react_comments.html
euth/comments/templatetags/react_comments.py
locale/de/LC_MESSAGES/django.po
package.json

fixes https://github.com/liqd/euth_wagtail/issues/87

2016 07 mn fix comment date

---

euth/comments/static/comments/react_comments.js
euth_wagtail/static/js/app.js
euth_wagtail/static/js/euth_wagtail.js
euth_wagtail/static/scss/components/_comments.scss
package.json
webpack.config.js

Rework how we use react. Rely more on props than state.Therefore reduce number of stateful components.

Change react state handling

---

euth/organisations/templates/euth_organisations/organisation_detail.html
euth_wagtail/settings/base.py
requirements.txt

you need to migrate to get started

add easy thumbnail

---

.gitignore
README.md
euth/comments/static/comments/react_comments.js
euth/comments/templates/comments/react_comments.html
euth/comments/templatetags/react_comments.py
euth_wagtail/settings/base.py
euth_wagtail/static/scss/core/_bootstrap.scss
euth_wagtail/templates/base.html
euth_wagtail/urls.py
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/djangojs.po
webpack.config.js

- also change were static files are looked up, because otherwise collection takes to much time

Js translations with django translation view

---

euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/static/js/euth_wagtail.js
euth_wagtail/static/scss/all.scss
euth_wagtail/static/scss/components/_org-page.scss
euth_wagtail/static/scss/core/_buttons.scss
euth_wagtail/static/scss/core/_hero-unit.scss
euth_wagtail/static/scss/core/_tabs.scss

2016 07 cc style projects

---

Procfile
README.md
euth/user_management/emails.py
euth/user_management/templates/emails/register.en.html
euth/user_management/templates/emails/register.en.txt
euth/user_management/templates/emails/reset.en.html
euth_wagtail/fixtures/site-dev.json
euth_wagtail/fixtures/site-heroku.com
euth_wagtail/fixtures/site-prod.json
euth_wagtail/fixtures/site-stage.json
euth_wagtail/settings/base.py
tests/user_management/test_views.py

Stop flood of clickable links in emails

---

euth/comments/static/comments/react_comments.js

Fix hardcoded urls in comments javascript

---

euth/comments/static/comments/react_comments.js

fixes https://github.com/liqd/euth_wagtail/issues/90

2016 07 mn change placeholder text

---

euth/ideas/templates/euth_ideas/idea_detail.html
euth_wagtail/static/scss/components/_action-bar.scss
euth_wagtail/static/scss/components/_ideas.scss
euth_wagtail/static/scss/core/_bootstrap-variables.scss

adjust idea detail page to designs

2016 07 mn better styling of idea detail

---

euth/ideas/models.py
euth/ideas/urls.py
euth/ideas/views.py
requirements/base.txt
tests/ideas/test_idea_models.py
tests/ideas/test_idea_views.py

this implements the suggestions made in  this PR https://github.com/liqd/euth_wagtail/pull/131

2016 07 mn better ck editor

---

euth/comments/migrations/0002_auto_20160712_0744.py
euth/comments/models.py
euth/comments/serializers.py
euth/comments/static/comments/react_comments.js
euth/contrib/base_models.py
euth/modules/migrations/0002_auto_20160715_1640.py
euth/modules/migrations/0003_replace_modelutils.py
euth/modules/models.py
euth/organisations/migrations/0007_auto_20160715_1640.py
euth/organisations/models.py
euth/projects/migrations/0003_auto_20160715_1640.py
euth/projects/models.py
euth/user_management/migrations/0002_auto_20160715_1640.py
euth/user_management/models.py
euth_wagtail/settings/test.py
pytest.ini
tests/apps/__init__.py
tests/apps/blog/apps.py
tests/apps/blog/migrations/0001_initial.py
tests/apps/blog/models.py
tests/contrib/conftest.py
tests/contrib/test_base_models.py

Replace model utils by custom base models

---

euth/organisations/templates/euth_organisations/includes/organisation_tile.html
euth_wagtail/static/scss/components/_accordion-block.scss
euth_wagtail/static/scss/components/_orgs.scss

2016 07 cc ui fixes

---

euth/ideas/templates/euth_ideas/includes/idea_list_tile.html
euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/static/scss/components/_ideas.scss
euth_wagtail/static/scss/core/_hero-unit.scss

see the FIXMEs on idea_list_tile.html - some missing data, otherwise easy stuff

2016 08 cc project list tidy

---

euth/ideas/templates/euth_ideas/idea_detail.html
euth_wagtail/static/scss/components/_ideas.scss
euth_wagtail/static/scss/core/_bootstrap-variables.scss

Some styling to the rate widget

Rate widget UI

---

euth/projects/templates/euth_projects/includes/project_tile.html
euth_wagtail/static/scss/components/_orgs.scss
euth_wagtail/static/scss/components/_projects.scss
euth_wagtail/static/scss/core/_tiles.scss

Improved project tile listing ui

Update to project tile

---

euth/ideas/templates/euth_ideas/idea_list.html
euth/ideas/templates/euth_ideas/includes/idea_list_tile.html
euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/settings/base.py
euth_wagtail/static/scss/all.scss
euth_wagtail/static/scss/components/_avatars.scss
euth_wagtail/static/scss/components/_ideas.scss
euth_wagtail/static/scss/components/_orgs.scss
euth_wagtail/static/scss/core/_badges.scss
euth_wagtail/static/scss/core/_bootstrap-variables.scss
euth_wagtail/static/scss/core/_hero-unit.scss
euth_wagtail/static/scss/core/_tabs.scss
euth_wagtail/static/scss/core/_tiles.scss

Visual improvements to the projects detail page including
1. The hero unit header
2. the ideas list
3. the ideas list "create proposal" button - this is dummy
there are dummy badges added to the informations tab.
if there's another ideas list in this landscape format its probably been messed up, I will do it in another branch

2016 08 cc ui improvements

---

euth/organisations/templates/euth_organisations/includes/organisation_tile.html
euth/organisations/templates/euth_organisations/organisation_list.html
euth_wagtail/static/scss/components/_orgs.scss

Clean up orgs tile

---

euth/comments/signals.py
tests/comments/conftest.py
tests/comments/test_model.py
tests/rates/test_rate_models.py

fixes https://github.com/liqd/euth_wagtail/issues/175

2016 08 mn delete rates on comment delete

---

tests/ideas/test_idea_models.py

Signed-off-by: Loic Dachary <loic@dachary.org>

add test for the ideas.comments property

---

docs/process-model.md

- describe what processes look like
- add tree house example

Add documentation on process model

---

euth/comments/static/comments/react_comments.js
euth/comments/templates/comments/react_comments.html
euth/comments/templatetags/react_comments.py
euth/ideas/phases.py
euth/ideas/templates/euth_ideas/idea_detail.html
euth/ideas/templates/euth_ideas/idea_list.html
euth/ideas/views.py
euth/modules/mixins.py
euth/modules/models.py
euth/phases/contents.py
euth/phases/models.py
euth/projects/mixins.py
euth/projects/models.py
euth/projects/templates/euth_projects/project_detail.html
euth/rates/static/rates/react_rates.js
euth/rates/templates/rates/react_rates.html
euth/rates/templatetags/react_rates.py
tests/apps/blog/phases.py
tests/phases/test_contents.py
tests/phases/test_models.py
tests/projects/conftest.py
tests/projects/test_mixins.py

This pull-request does not ensure that votingd/commenting is disabled on Idea detail pages. Because it doesn't deal with detail pages yet.

 Add additional phases to idea collection

---

euth/rates/static/rates/react_rates.js
euth_wagtail/static/scss/core/_type.scss

was 700, now is 400 as the default font weight is 400.

fixed bad font weight on headings

---

euth/contrib/widgets.py
euth/ideas/forms.py
euth/ideas/templates/euth_ideas/idea_form.html
euth/ideas/views.py
euth_wagtail/static/js/euth_wagtail.js
euth_wagtail/static/scss/components/_forms.scss
euth_wagtail/static/scss/core/_bootstrap.scss

Improve image upload widget

---

euth/organisations/templates/euth_organisations/organisation_detail.html
euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/static/scss/components/_hero-unit.scss
euth_wagtail/static/scss/components/_orgs.scss

add white circle beneath hero-unit logos,
increase social media icon size and space
fixes #228

styling changes for hero unit

---

euth/rates/static/rates/react_rates.js
euth_wagtail/static/scss/components/_comments.scss
euth_wagtail/static/scss/components/_ideas.scss

change style for rating buttons on mobile

---

projects/templates/projects/projects_page.html

Fix errors in wagtail projects page template

---

euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/static/js/euth_wagtail.js
euth_wagtail/static/scss/core/_tabs.scss

add logic for default tab,
add hash-navigation for tabs

improve tab handling

---

euth/comments/static/comments/react_comments.js
euth/ideas/templates/euth_ideas/includes/modal.html
euth/reports/static/reports/react_reports.js
euth_wagtail/static/scss/components/_modal.scss

- change texts for modals (password reset),
- style report success modal,
- change button classes for modals,
- change backdrop color,
- remove shadow from modal

Update modal styling

---

euth/ideas/templates/euth_ideas/idea_list.html
euth/ideas/templates/euth_ideas/includes/idea_list_tile.html
euth_wagtail/static/scss/components/_ideas.scss
euth_wagtail/static/scss/core/_badges.scss
euth_wagtail/static/scss/core/_tabs.scss

change proposals list style for mobile
change create proposal button style for mobile
fix styling for tabs on mobile
add more space between badges for mobile
fix images not being full height when the title gets longer
prevent line breaks inside date and meta items
fixes #237, #235

update proposals page style

---

euth/user_management/templates/emails/register.en.html
euth_wagtail/templates/email_base.html

update activation mail

---

euth/dashboard/views.py
euth/ideas/rules.py
euth/ideas/views.py
euth/modules/predicates.py
euth/phases/predicates.py
euth/projects/models.py
euth/projects/predicates.py
euth/projects/rules.py
euth_wagtail/settings/base.py
requirements/base.txt
tests/ideas/conftest.py
tests/ideas/test_idea_views.py
tests/utils.py

- prevent creation of ideas by users if the phase doesn't allows creating ideas

Change permissions depending on phase

---

euth/comments/serializers.py
euth/comments/static/comments/react_comments.js
euth_wagtail/static/scss/components/_comments.scss

fix typo,
improve margins,
fix invalid markup

finetunes comment list

---

euth/user_management/templates/user_management/reset_password.html

changed reset dialog button style and wording

---

euth/rates/static/rates/react_rates.js
euth_wagtail/static/scss/components/_ideas.scss

added read-only state to rating buttons for ideas

---

euth/user_management/forms.py
tests/user_management/test_views.py

Fix user management bugs

---

euth/comments/static/comments/react_comments.js
euth/contrib/static/js/api.js
euth/contrib/static/js/app.js
euth/rates/static/rates/react_rates.js
euth/reports/static/reports/react_reports.js
euth_wagtail/static/js/app.js
euth_wagtail/static/scss/components/_modal.scss
webpack.config.js

add api module for all the requests to the API,
move js for opin to euth/contrib,
toggle class on body for loading indicator,
add style for XHR feedback
fixes #213

refactor XHR code

---

euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/base_dashboard.html
euth/dashboard/templates/euth_dashboard/project_form.html
euth/dashboard/templates/euth_dashboard/project_list.html
euth/dashboard/urls.py
euth/dashboard/views.py
euth_wagtail/static/scss/all.scss
euth_wagtail/static/scss/components/_dashboard.scss
euth_wagtail/static/scss/components/_label.scss
euth_wagtail/static/scss/components/_projects.scss
euth_wagtail/static/scss/core/_bootstrap-variables.scss
euth_wagtail/static/scss/core/_bootstrap.scss
euth_wagtail/static/scss/core/_buttons.scss
euth_wagtail/static/scss/core/_tabs.scss
tests/dashboard/test_dashboard_views.py
tests/organisations/factories.py

Extend dashboard with project listing functions

---

euth/documents/admin.py
euth/documents/apps.py
euth/documents/migrations/0001_initial.py
euth/documents/models.py
euth/documents/phases.py
euth/documents/templates/euth_documents/document_detail.html
euth/documents/templates/euth_documents/paragraph_detail.html
euth/documents/urls.py
euth/documents/views.py
euth/ideas/rules.py
euth_wagtail/settings/base.py
euth_wagtail/urls.py

@vellip can you do the styling of the commenting text, styles are here: https://zpl.io/Z2qB842

2016 09 mn add commenting paragraphs

---

euth/dashboard/templates/euth_dashboard/base_dashboard.html
euth/dashboard/templates/euth_dashboard/dashboard_overview.html
euth/dashboard/templates/euth_dashboard/profile_detail.html
euth/dashboard/templates/euth_dashboard/project_form.html
euth/dashboard/templates/euth_dashboard/project_list.html
euth_wagtail/static/scss/components/_dashboard.scss

restyle dashboard navigation

---

home/templates/home/home_page.html

add heading for slider on landing page

---

euth/documents/models.py
euth_wagtail/settings/base.py
euth_wagtail/static/scss/components/_commenting-text.scss

fix hover style for commenting text

---

euth/organisations/templates/euth_organisations/organisation_detail.html
euth/organisations/views.py
euth/projects/models.py

filter drafts

---

euth_wagtail/static/js/euth_wagtail.js
euth_wagtail/static/scss/components/_carousel.scss
euth_wagtail/static/scss/components/_projects.scss

redo slider styling/behavior

---

euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/project_form.html
euth/projects/migrations/0002_auto_20160912_0917.py
euth/projects/migrations/0002_project_result.py
euth/projects/models.py
euth/projects/templates/euth_projects/project_detail.html

add results field to projects model,
fix information output to respect paragraphs and linebreaks

add results field

---

euth/organisations/admin.py
euth/projects/admin.py

- add better widget for adding and removing user from project / organisations

Improve project and organisation admin

---

euth/users/templates/emails/reset.en.html

fix wording for reset email

---

euth/modules/models.py
euth_wagtail/static/scss/components/_carousel.scss
euth_wagtail/static/scss/components/_ideas.scss
euth_wagtail/static/scss/components/_projects.scss
euth_wagtail/static/scss/core/_tiles.scss

make org name always stick to the bottom,
remove letter-spacing on tiles,
reduce line-height on tiles,
remove some text-align: justify,
fixed typo in model

minor changes after deployment

---

euth/users/templates/euth_users/indicator_menu.html
euth_wagtail/static/scss/components/_menus.scss

fix markup and styling for logout form

---

euth/dashboard/templates/euth_dashboard/project_list.html
euth/dashboard/views.py

send user back to project detail page after editing it,
add link to detail page on projects listing view

improve UX on projects listing and editing page 

---

contrib/transforms/html_transforms.py
euth/projects/migrations/0003_auto_20160914_0750.py
euth/projects/models.py
euth_wagtail/settings/base.py
euth_wagtail/static/scss/components/_forms.scss
euth_wagtail/urls.py

add image upload functionality for CK editor

---

euth_wagtail/static/scss/components/_menus.scss
euth_wagtail/static/scss/core/_footer.scss
euth_wagtail/templates/includes/footer.html
euth_wagtail/templates/includes/top_menu.html

reduce header height for mobile
improve footer for mobile
closes #310

update header and footer styling

---

euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/static/scss/components/_hero-unit.scss

fix left styling issues on project detail page

---

euth/ideas/templates/euth_ideas/idea_detail.html
euth_wagtail/static/scss/components/_comments.scss
euth_wagtail/static/scss/components/_ideas.scss

idea detail styling

---

euth/documents/templates/euth_documents/document_detail.html
euth_wagtail/static/scss/components/_commenting-text.scss
euth_wagtail/static/scss/core/_bootstrap-variables.scss
euth_wagtail/static/scss/core/_buttons.scss

adjust mobile for commenting text
closes #312

new style for commenting text

---

euth/contrib/static/js/dateTimeInput.js
euth/contrib/widgets.py
euth/dashboard/templates/euth_dashboard/project_form.html
euth_wagtail/settings/base.py
euth_wagtail/static/scss/core/_bootstrap-variables.scss
package.json

remove bootstrap border radius,
add contrib as app,
add datepicker

add datepicker

---

euth/dashboard/blueprints.py
euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/blueprint_list.html
euth/dashboard/templates/euth_dashboard/project_list.html
euth/dashboard/urls.py
euth/dashboard/views.py
euth/documents/phases.py
euth/ideas/phases.py
euth/phases/predicates.py
euth_wagtail/static/scss/components/_dashboard.scss
tests/dashboard/test_dashboard_views.py

Allows to select upon project create what phases the project has.

Selector for project blueprints

---

euth_wagtail/static/scss/components/_dashboard.scss

display dropdown menu as wide as longest entry

---

euth/dashboard/templates/euth_dashboard/project_form.html
euth/dashboard/views.py

add heading to project create/update form

---

euth_wagtail/static/scss/all.scss
euth_wagtail/static/scss/components/_ck-editor.scss
euth_wagtail/static/scss/components/_forms.scss
euth_wagtail/static/scss/components/_info-number.scss

Refactor styling for ck editor and dashboard

---

Makefile

- remove test running from test-clean
- add command to run only last failed

Improve makefile test commands

---

euth/phases/models.py
tests/projects/test_project_models.py

add odering to phases model

---

euth/comments/static/comments/CommentBox.jsx
euth/comments/static/comments/CommentForm.jsx
euth/contrib/static/js/config.js
euth/ratings/static/ratings/react_ratings.jsx
euth_wagtail/static/scss/components/_rating.scss

add "please login to comment",
fix config for login url
fixes #375, fixes #380

fix bad rating style when no rating is allowed,

---

euth/documents/apps.py
euth/documents/models.py
euth/documents/signals.py
tests/documents/test_document_models.py

Mn 2016 delete comments of deleted document and paragraphs

---

euth/contrib/static/js/api.js
euth/documents/static/documents/ParagraphBox.js
euth_wagtail/settings/base.py

Use json in all rest APIs

---

.tx/config
docs/process-model.md
docs/transifex.md
home/locale/da/LC_MESSAGES/django.po
home/locale/de/LC_MESSAGES/django.po
home/locale/en/LC_MESSAGES/django.po
home/locale/fr/LC_MESSAGES/django.po
home/locale/it/LC_MESSAGES/django.po
home/locale/sl/LC_MESSAGES/django.po
home/locale/sv/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/djangojs.po
requirements/dev.txt

add transifex client,
add tx config,
update translation files

add transifex

---

euth/comments/static/comments/CommentForm.jsx
euth/documents/models.py
euth/documents/phases.py
euth/documents/serializers.py
euth/documents/templates/euth_documents/document_detail.html
tests/documents/test_document_models.py

Add generic relations to documents

---

euth/documents/static/documents/Paragraph.js
euth/documents/static/documents/ParagraphBox.js
euth_wagtail/static/scss/components/_document.scss
euth_wagtail/static/scss/core/_buttons.scss
euth_wagtail/static/scss/core/_mixins.scss
package.json

- add animation
- prevent creation of new paragraphs from moving
- prevent creating multiple document on first create
- lower up and down flickering by resizing textareas
solves #381 ???

improve paragraph edit form

---

euth/comments/api.py
euth/comments/migrations/0002_change_comment_default_odering.py
euth/comments/models.py
euth/comments/serializers.py
euth/comments/static/comments/Comment.jsx
euth_wagtail/settings/base.py
tests/comments/test_api.py

Fix recursion issue comments api

---

euth_wagtail/static/scss/core/_bootstrap-variables.scss

This should fix yesterday's fix.

Color Palette Fix

---

euth/contrib/services.py
euth/contrib/static/js/imageUploader.js
euth/contrib/templates/euth_contrib/image_upload_widget.html
euth/contrib/widgets.py
euth/dashboard/templates/euth_dashboard/organisation_form.html
tests/contrib/test_widgets.py
tests/organisations/test_models.py

fixes #335
fixes #236 
fixes #261

rework image upload widget

---

euth/comments/api.py
euth/comments/migrations/0003_use_usergenerated_content_base_model.py
euth/comments/models.py
euth/comments/serializers.py
euth/contrib/api/permissions.py
euth/contrib/base_models.py
euth/memberships/models.py
euth/modules/models.py
euth/ratings/api.py
euth/ratings/migrations/0002_use_usergenerated_content_base_model.py
euth/ratings/models.py
euth/ratings/serializers.py
euth/ratings/templatetags/react_ratings.py
euth/reports/api.py
euth/reports/emails.py
euth/reports/migrations/0002_use_usergenerated_content_base_model.py
euth/reports/models.py
euth/reports/serializers.py
tests/comments/factories.py
tests/comments/test_api.py
tests/ratings/factories.py
tests/ratings/test_rating_api.py
tests/ratings/test_rating_models.py
tests/reports/factories.py

Unify user attributes for various types

---

euth/documents/templates/euth_documents/document_detail.html
euth_wagtail/static/scss/components/_commenting-text.scss
euth_wagtail/static/scss/core/_blocks.scss
euth_wagtail/static/scss/core/_bootstrap-variables.scss
euth_wagtail/static/scss/core/_buttons.scss

button styles are now more consistent

ghost button kill and more button style fixes

---

euth/contrib/templates/euth_contrib/includes/info_note.html
euth/projects/templates/euth_projects/project_detail.html

still missing the image, but I would suggest to add the image in a later PR.

Mn 2016 10 display info for project that have not started

---

euth/dashboard/forms.py
euth/dashboard/views.py
euth/documents/rules.py
euth/ideas/rules.py
euth/ideas/views.py
euth/modules/predicates.py
tests/dashboard/test_dashboard_views.py
tests/ideas/test_idea_views.py

- initiators can now view ideas of private processes
- initiator of project is automatically moderator
fixes #342 
fixes #364

Fix permission handling

---

euth/projects/static/euth_projects/timeline-popover.js
euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/static/scss/components/_timeline.scss

properly hide popover after dismissing them by clicking somewhere else,
make the dots bigger on mobile

improve timeline behavior

---

euth/flashpoll/templates/euth_flashpoll/flashpoll_detail.html
euth/phases/models.py
euth/projects/mixins.py
euth/projects/models.py
euth/projects/templates/euth_projects/project_detail.html
tests/phases/factories.py
tests/phases/test_phases_models.py
tests/projects/test_mixins.py
tests/projects/test_project_models.py

- ensure that after the last phase of project the text doesn't ask to wait for the next phase
- move more behaviour from the project mixin to project model (fat model)
- fix project factory

Refactor last phase handling

---

euth/dashboard/forms.py
euth/users/migrations/0003_rename_avatar_field.py
euth/users/models.py
euth_wagtail/templates/account/signup.html
euth_wagtail/templates/socialaccount/signup.html
tests/users/test_models.py

Mn 2016 11 fix social login

---

euth/projects/templates/euth_projects/includes/project_hero_unit.html
euth_wagtail/assets/scss/components/_hero-unit.scss

add a link for organisation from project detail

---

euth/dashboard/templates/euth_dashboard/base_dashboard.html
euth/organisations/templates/euth_organisations/includes/organisation_tile.html
euth/organisations/templates/euth_organisations/organisation_detail.html
euth/projects/templates/euth_projects/includes/project_tile.html

- allows user to set display name of organisation
- allows user to translate display name of organisation

replace usage of organisation name with title

---

euth_wagtail/assets/js/euth_wagtail.js
euth_wagtail/assets/scss/components/_carousel.scss
home/templates/home/home_page.html

let the slider start at 0
fixes #441

fix slider for safari

---

euth/comments/api.py
euth/comments/static/comments/CommentBox.jsx
euth/comments/templatetags/react_comments.py
euth/documents/api.py
euth/documents/models.py

Mn 2016 11 remove comment list

---

euth_wagtail/assets/scss/components/_projects.scss

positioning of labels on project teasers

---

euth/documents/static/documents/ParagraphBox.jsx

I got the following error message:
.../euth_wagtail/euth/documents/static/documents/ParagraphBox.jsx
113:11  error  Closing curly brace should be on the same line as opening curly brace or on the line after the previous block  brace-style
140:11  error  Closing curly brace should be on the same line as opening curly brace or on the line after the previous block  brace-style

Fix lint errors

---

euth/dashboard/templates/euth_dashboard/includes/project_form_result_tab.html
euth/projects/migrations/0008_add_help_text_for_result.py
euth/projects/models.py
euth/projects/templates/euth_projects/project_detail.html

Improve result description

---

euth_wagtail/assets/scss/components/_avatars.scss

stop hiding date on mobile

---

euth/projects/templates/euth_projects/includes/project_hero_unit.html
euth_wagtail/assets/scss/components/_hero-unit.scss

style link in project header
fixes #486

remove organisation logo from project header,

---

euth/contrib/templates/euth_contrib/includes/info_note.html
euth_wagtail/assets/scss/components/_info-note.scss

adjust info-note classname to follow new convention,
smaller spaces above and below infonote
fixes #443

info-note changes

---

euth/comments/models.py
euth/comments/static/comments/Comment.jsx
euth/comments/templatetags/react_comments.py
euth/projects/templates/euth_projects/includes/project_hero_unit.html
euth_wagtail/assets/scss/components/_hero-unit.scss
package.json
webpack.config.js

remove markdown dependency,
show moderator badge only if not deleted,
fix comment sorting to be correct again,
safely escape comments
fixes #493 and closes #363

comment fixes

---

euth_wagtail/assets/js/euth_wagtail.js
euth_wagtail/assets/scss/components/_carousel.scss
package.json
webpack.config.js

move from owl carousel to slick slider

---

euth/dashboard/templates/euth_dashboard/project_list.html
euth/projects/templates/euth_projects/includes/project_list_item.html
euth/users/migrations/0006_change_avatar_validator_and_helptext.py
euth/users/models.py
euth/users/templates/euth_users/user_detail.html
euth/users/views.py
euth_wagtail/assets/js/euth_wagtail.js
euth_wagtail/assets/scss/all.scss
euth_wagtail/assets/scss/components/_carousel.scss
euth_wagtail/assets/scss/components/_hero-unit.scss
euth_wagtail/assets/scss/components/_teaserlist.scss
euth_wagtail/assets/scss/core/_utilities.scss
euth_wagtail/settings/base.py
package.json
webpack.config.js

is based on #511, merge that first for correct change view

Pv 2016 11 user profile

---

euth_wagtail/assets/scss/components/forms/_form-control-upload.scss
euth_wagtail/assets/scss/components/forms/_general-form.scss
euth_wagtail/assets/scss/core/_bootstrap-variables.scss

form and text styling #492

---

euth_wagtail/assets/scss/components/_hero-unit.scss
euth_wagtail/assets/scss/wagtail-blocks/_accordion-block.scss

orga page hero and accordion fix #463

---

euth/comments/static/comments/Comment.jsx
euth_wagtail/assets/scss/components/_comments.scss
euth_wagtail/templates/base.html

smaller style changes,
change time handling for comments, fixes #321

add language code to JS,

---

euth/dashboard/templates/euth_dashboard/includes/project_form_participation_tab.html

hide phases by default

---

euth/comments/static/comments/Comment.jsx

hide date for deleted comments

---

euth/follows/serializers.py
euth/follows/static/follows/FollowButton.jsx
euth/follows/templatetags/follow_tags.py
euth/projects/templates/euth_projects/includes/project_list_item.html
euth/users/templates/euth_users/indicator_menu.html
euth_wagtail/assets/scss/components/_hero-unit.scss
euth_wagtail/assets/scss/components/_menus.scss
euth_wagtail/assets/scss/components/_user-indicator.scss
euth_wagtail/assets/scss/core/_bootstrap.scss
euth_wagtail/assets/scss/core/_buttons.scss

add follower count to button,
add btngroup,
add template tag to follows to check if following,
add following and member indication to profile's project list,
update menu

Pv 2016 11 change follow button and update profile

---

euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/base_dashboard.html
euth/dashboard/templates/euth_dashboard/includes/dropdown.html
euth/dashboard/templates/euth_dashboard/profile_detail.html
euth/users/migrations/0006_update_gender_change_verbose_names.py
euth/users/migrations/0007_update_gender_options_and_helptexts_verbose_names.py
euth/users/models.py
euth/users/templates/euth_users/user_detail.html
euth_wagtail/assets/scss/components/_dashboard-nav.scss

Pv 2016 11 update profile form

---

euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/project_invites.html

improve invite form ux

---

euth/dashboard/templates/euth_dashboard/project_list.html
euth_wagtail/assets/scss/components/_projects.scss
euth_wagtail/assets/scss/core/_buttons.scss

update dashboard project list,
add proper .btn-sm style

add follower number to dashboard

---

euth/memberships/templates/euth_memberships/invite_form.html
euth/memberships/templates/euth_memberships/request_detail.html
euth/projects/rules.py
euth/projects/templates/euth_projects/includes/project_hero_unit.html
euth/projects/views.py

hide follow button if not in private project
fixes #502

update request and accept invite page

---

euth/documents/static/documents/Paragraph.jsx
euth/documents/static/documents/ParagraphBox.jsx

add text to add paragraph button

---

euth_wagtail/assets/scss/components/_hero-unit.scss

add white background to avatar on profile

---

euth_wagtail/assets/scss/core/_footer.scss

shrink eu flag on mobile

---

euth/follows/templatetags/react_follows.py
euth/projects/templates/euth_projects/includes/project_hero_unit.html

rename rule to be conform with naming convention,
make follow button in span instead for inline display

add edit button to project detail page,

---

euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/assets/scss/components/_hero-unit.scss
euth_wagtail/assets/scss/components/_label.scss

Pv 2016 12 styling fixes

---

euth/actions/emails.py
euth/actions/signals.py
euth/comments/signals.py
euth_wagtail/settings/base.py
tests/actions/test_actions.py

Notify moderators without extra field in action table

Mn 2016 11 notify moderators on idea added2

---

euth/actions/signals.py
tests/actions/test_actions.py

- filter moderators from notifications if they are the actor
- use project for target of item actions (instead of module)

Fix small notifications issues

---

euth/ideas/templates/euth_ideas/idea_list.html
euth/projects/templates/euth_projects/project_detail.html
euth_wagtail/assets/scss/components/_ideas.scss

narrow & medium containers on project page for better readability
fixes #517

readability on project page #517

---

euth_wagtail/assets/scss/components/_menus.scss

fix mobile dropdown

---

euth/dashboard/forms.py
euth/dashboard/views.py
tests/dashboard/test_dashboard_views.py

add comma validation to invite form

---

euth/dashboard/forms.py
requirements/base.txt

belongs to https://github.com/liqd/adhocracy4/pull/12

set weight in dashboard

---

euth/follows/templatetags/follow_tags.py
euth/projects/templates/euth_projects/includes/project_hero_unit.html

Mn 2017 01 bugfixes

---

euth/contrib/oembed.py
euth_wagtail/settings/base.py
requirements/base.txt

implements https://github.com/coleifer/micawber
for django integration: https://github.com/coleifer/micawber/blob/master/docs/django.rst
spec: http://oembed.com/
providers: http://oembed.com/#section7

add oembed

---

euth/maps/templates/euth_maps/mapidea_list.html
euth_wagtail/assets/scss/components/_maps.scss

issue fixing for milestone

---

euth_wagtail/assets/scss/core/_buttons.scss

fix issues with fixed header and anchor jump links

---

euth/memberships/templates/euth_memberships/request_detail.html
euth_wagtail/assets/js/euth_wagtail.js
euth_wagtail/assets/scss/components/_carousel.scss

Pv 2017 01 fix slider causing trouble on mobile

---

euth/dashboard/templates/euth_dashboard/project_list.html
euth/memberships/forms.py
euth/memberships/templates/euth_memberships/invite_form.html
euth/memberships/views.py
tests/memberships/test_memberships_models.py
tests/memberships/test_memberships_views.py

update test for invitation, fixes #592

allow invitation acceptance only for same emails,

---

euth_wagtail/assets/scss/components/_ideas.scss
euth_wagtail/assets/scss/components/_user-indicator.scss

Pv 2017 01 fix anchor scroll

---

euth_wagtail/assets/scss/components/_ideas.scss

fix idea body with long titles

---

euth_wagtail/assets/scss/all.scss
euth_wagtail/assets/scss/wagtail-blocks/_richtext-block.scss
euth_wagtail/assets/scss/wagtail-blocks/_video-block.scss
home/wagtail_hooks.py
webpack.config.js

Mn 2017 02 fix responsive video

---

euth/organisations/views.py
euth_wagtail/assets/scss/components/_hero-unit.scss
tests/organisations/test_views.py

fixes #555 
fixes #603 
fixes #544

Pv 2017 01 styling issues

---

euth/users/api.py
tests/users/test_api.py

add tests for user api

---

euth_wagtail/templates/a4projects/project_detail.html

move template to right directory

---

euth/contrib/api/permissions.py
euth/contrib/static/js/app.js
euth/dashboard/forms.py
euth/dashboard/static/user_list/UserListItem.jsx
euth/dashboard/static/user_list/react_user_list.jsx
euth/dashboard/templates/euth_dashboard/project_users.html
euth/dashboard/templatetags/react_user_list.py
euth/dashboard/views.py
euth/projects/api.py
euth/projects/serializers.py
euth/users/fields.py
euth/users/serializers.py
euth/users/static/users/js/user_search.js
euth/users/widgets.py
euth_wagtail/assets/scss/all.scss
euth_wagtail/assets/scss/components/_table-list.scss
euth_wagtail/assets/scss/components/_tabs.scss
euth_wagtail/assets/scss/core/_bootstrap-variables.scss
euth_wagtail/assets/scss/core/_type.scss
euth_wagtail/urls.py

add moderators from usersearchfield

add usersearchfield

---

euth_wagtail/templates/403.html

wrong commit message, adds 403 template

add 403 template

---

euth/maps/static/js/custom/map_choose_point.js
euth/maps/static/js/custom/map_choose_polygon.js
euth/maps/static/js/custom/map_display_point.js

remove mouse wheel zooming from maps, fixes #622

map zooming

---

euth/users/templates/euth_users/user_detail.html

profile: remove trailing comma

---

euth/dashboard/templates/euth_dashboard/project_form.html
euth_wagtail/assets/scss/components/_maps.scss

improve js/css project form order, fix leaflet top/bottom zindex

---

euth_wagtail/assets/scss/components/forms/_skinny-form.scss

fix login tabs

---

euth_wagtail/assets/scss/components/_comments.scss

allow line breaks in comments-text

---

home/migrations/0017_auto_20170206_1103.py
home/models.py
home/templates/home/blocks/page_collection_block.html
home/templates/home/manuals_detail_page.html

this removes the highlighted page and adds an optional intro_text instead
ignore commit message

change pagecollection model

---

euth/ideas/models.py
package.json
requirements/base.txt

fix #601 
first part of adhocracy4 updates

use a4 idea queryset

---

euth_wagtail/settings/base.py
package.json
requirements/base.txt

update app configs in settings

---

euth_wagtail/assets/scss/components/_hero-unit.scss
euth_wagtail/assets/scss/core/_buttons.scss

This will fix #617 (Icon Color)

Dm 2017 02 10 icon styling

---

euth/organisations/views.py

Sort projects on organisation detail page

---

euth/memberships/forms.py
euth/memberships/templates/euth_memberships/invite_form.html
euth/memberships/views.py
tests/memberships/test_memberships_models.py
tests/memberships/test_memberships_views.py

Revert pull request #605

---

euth/dashboard/forms.py
euth/dashboard/static/language_switch/react_language_switch.jsx
requirements/base.txt
tests/dashboard/test_dashboard_views.py

Dashboard organisation form allow deletion

---

euth/dashboard/templates/euth_dashboard/includes/project_form_participation_tab.html
euth_wagtail/assets/scss/components/_phase-form.scss

change button styling and text

---

euth/actions/emails.py
euth/contrib/emails.py

- send each receiver thier own copy of the email

Implement receiver spliting for emails

---

euth/maps/static/js/custom/map_choose_point.js
euth/maps/static/js/custom/map_choose_polygon.js
euth/maps/static/js/custom/map_display_point.js
euth/maps/static/js/custom/map_display_points.js
euth/maps/templates/euth_maps/mapidea_list.html

Mn 2017 02 fix map issues

---

euth/flashpoll/services.py
euth_wagtail/settings/base.py

Sorry @MagdaN , 
This is the real pull request, forget the other one.

added APIKey and fixed bug on results showing

---

euth/dashboard/templatetags/form_tags.py
euth/offlinephases/admin.py
euth/offlinephases/models.py
euth/offlinephases/rules.py
euth/offlinephases/templates/euth_offlinephases/offlinephase_detail.html
euth/offlinephases/templates/euth_offlinephases/offlinephase_form.html
euth/offlinephases/validators.py
euth_wagtail/settings/base.py
tests/offlinephases/conftest.py
tests/offlinephases/factories.py
tests/offlinephases/test_views.py

improve fileupload form

---

tests/users/test_api.py

fix user test

---

euth/offlinephases/templates/euth_offlinephases/offlinephase_detail.html

add text if no documentation has been added

---

euth/offlinephases/forms.py
euth/offlinephases/templates/euth_offlinephases/file_upload_widget.html
euth/offlinephases/widgets.py

this is pretty similar to the image upload widget in core, we should check, if this is needed in core also.

add file upload widget

---

euth_wagtail/assets/scss/core/_tiles.scss

fix fontsize

---

euth/projects/templates/euth_projects/includes/project_tile.html
euth_wagtail/assets/scss/components/_projects.scss
euth_wagtail/assets/scss/core/_tiles.scss

fix styling issues

---

euth/users/serializers.py

use small in image in api

---

euth/blueprintsuggest/blueprints.py
euth/blueprintsuggest/templates/euth_blueprintsuggest/form.html
euth_wagtail/assets/scss/components/_dashboard.scss

Mn 2017 03 fix dst wording issues

---

euth/dashboard/templates/euth_dashboard/blueprint_list.html
euth/dashboard/templates/euth_dashboard/organisation_form.html
euth/dashboard/templates/euth_dashboard/project_invites.html
euth/dashboard/templates/euth_dashboard/project_list.html
euth/dashboard/templates/euth_dashboard/project_users.html
euth/ideas/templates/euth_ideas/includes/modal.html
euth_wagtail/assets/scss/core/_buttons.scss

Mn 2017 03 fix button text size

---

euth/dashboard/templates/euth_dashboard/includes/project_form_information_tab.html
euth_wagtail/assets/scss/components/_info-number.scss
euth_wagtail/assets/scss/components/forms/_general-form.scss

fixes #628 and makes form validation error messages stand out.

form alert for dashboard and proposals

---

.tx/config
euth/contrib/management/commands/makemessages.py
euth/dashboard/templates/euth_dashboard/includes/project_form_result_tab.html
locale/da/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/django.po
locale/ru/LC_MESSAGES/django.po
locale/ru/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po
locale/uk/LC_MESSAGES/django.po
locale/uk/LC_MESSAGES/djangojs.po

fixes #740 (I hope)
What I did:
1. fix my local translation files (.po files) -> remove wrong translations that where marked with 'fuzzy'
2. pull strings from transifex
3. check for and fix fuzzy issues
4. run makemessages localy and check for and fix fuzzy issues
5. update makemessages in a way that only a4 and euth strings are added
6. rerun makemessages to add a4 strings

Mn 2017 03 update translations

---

euth/dashboard/templates/euth_dashboard/project_form.html
euth_wagtail/assets/scss/components/_dashboard.scss
euth_wagtail/assets/scss/components/forms/_general-form.scss

Add global error message to project dashboard

---

euth_wagtail/assets/scss/components/_comments.scss
euth_wagtail/assets/scss/components/_dropdown.scss
euth_wagtail/assets/scss/components/_menus.scss

slight styling improvement in language dropwdown

---

euth/dashboard/templates/euth_dashboard/profile_detail.html

adisplay error messages in profile forms

---

euth/projects/emails.py
tests/projects/test_api.py

Mn 2017 03 fix emails and add tests

---

euth/users/signals.py

Fix delete_images in user signals

---

euth_wagtail/assets/scss/components/_avatars.scss
euth_wagtail/assets/scss/components/_dividers.scss
euth_wagtail/assets/scss/components/_ideas.scss
euth_wagtail/assets/scss/components/_label.scss
euth_wagtail/assets/scss/components/_rating.scss
euth_wagtail/assets/scss/core/_buttons.scss

Did some work on the typography in idea collection and idea detail.

Idea Collection Styling and Typography

---

home/migrations/0020_homepage_add_editable_header.py
home/models.py
home/templates/home/includes/wagtail_hero_unit.html

* making the homepage's header subtitle editable

Mkind 2017 04 editable header

---

euth_wagtail/urls.py
euth_wagtail/urls_accounts.py

Mn 2017 03 change language login page

---

euth/users/__init__.py
euth/users/adapters.py
euth/users/templatetags/userindicator.py

Sanitizing next parameter

---

euth/dashboard/forms.py

Make settings widgets method static

---

euth/contrib/filters.py
euth/contrib/templates/euth_contrib/widgets/dropdown_link.html
euth/contrib/widgets.py
euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/project_form.html
euth/dashboard/templates/euth_dashboard/project_list.html
euth/dashboard/views.py
euth/organisations/templates/euth_organisations/organisation_detail.html
euth/organisations/views.py
euth/projects/templates/euth_projects/includes/project_hero_unit.html
euth/projects/templates/euth_projects/includes/project_tile.html
euth/projects/templatetags/project_class_tags.py
euth_wagtail/assets/scss/all.scss
euth_wagtail/assets/scss/components/_dashboard.scss
euth_wagtail/assets/scss/components/_filter_bar.scss
euth_wagtail/assets/scss/components/_label.scss
euth_wagtail/assets/scss/components/_projects.scss
tests/dashboard/test_dashboard_views.py

* sending `archive` in POST edit request will set a project's `is_archive` flag
* the flag requires that no phase is running anymore
* the project dashboard only shows the `archive` button if project is archivable (not yet archived and no phase left running)
* organisation view does not show archived projects anymore
* archived projects have an `archived` label in project list

Archiving projects

---

euth/contrib/static/js/app.js
euth_wagtail/templates/base.html
webpack.config.js

Improve momentjs integration

---

euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/project_form.html
euth/dashboard/templates/euth_dashboard/project_list.html
euth/dashboard/templatetags/form_tags.py
euth/dashboard/urls.py
euth/dashboard/views.py
euth_wagtail/assets/scss/components/_dashboard.scss
euth_wagtail/assets/scss/components/forms/_general-form.scss
package.json
requirements/base.txt
tests/dashboard/test_dashboard_views.py

* Adding un-/archiving buttons in dashboard project list instead of project update form
* Archived projects are not editable anymore

Archiving projects via projectlist

---

euth/dashboard/templates/euth_dashboard/project_list.html

Fixing dashboard's project list filter issue in issue #815 .

fixing issue 815

---

euth/organisations/templates/euth_organisations/organisation_detail.html

fixing issue #806

---

home/templates/home/includes/wagtail_hero_unit.html

made "play video" translatable

---

euth/dashboard/forms.py

fixes #804

---

euth/projects/templates/euth_projects/project_detail.html
euth/projects/templatetags/time_delta_tags.py
euth_wagtail/assets/scss/core/_tabs.scss
tests/projects/test_templatetags.py

missing: 
- design
- test (how do I test template tags?)

added time left to participate

---

euth/blueprints/forms.py
euth/blueprints/templates/euth_blueprints/form.html
euth/blueprints/templates/euth_blueprints/includes/breadcrumbs.html
euth/blueprints/templates/euth_blueprints/includes/step-aim.html
euth/blueprints/templates/euth_blueprints/includes/step-feasibility.html
euth/blueprints/templates/euth_blueprints/includes/step-finetuning-2.html
euth/blueprints/templates/euth_blueprints/includes/step-finetuning.html
euth/blueprints/templates/euth_blueprints/result.html
euth/blueprints/views.py
tests/blueprints/test_algorithm.py
tests/blueprints/test_views.py

* cleans up the DST templating by moving different things in different files
* introduces second fine tuning step in DST
* introduces time needed in hours per week in DST result
* fixes typo in complexity calculation

Mkind 2017 05 dst frontend

---

euth/blueprints/views.py
tests/blueprints/test_views.py

* Fixes a bug found by @SabineJulia that was trigged by using the fallback DST result. For the fallback there was no `timeneeded` calculation.  
* adding regression test

Mkind 2017 05 fixing dst no hour bug

---

euth/blueprints/forms.py
euth/blueprints/static/euth_blueprintsuggest/js/blueprintsuggest.js
euth/blueprints/templates/euth_blueprints/includes/step-finetuning.html
euth/blueprints/views.py
tests/blueprints/test_views.py

* fixing KeyError in backend
* fixing AttributeError in backend
* writing regression tests

Mkind 2017 05 fixing blueprint bugs

---

euth/dashboard/templates/euth_dashboard/project_users.html

Clarify user managment form for public projects

---

euth/contrib/middleware.py
euth_wagtail/urls.py
euth_wagtail/urls_accounts.py
tests/blueprints/test_views.py
tests/maps/conftest.py

satisfying linter

---

euth/documents/views.py
euth/ideas/views.py
euth/memberships/views.py
euth/offlinephases/views.py
euth/projects/mixins.py
euth/projects/templates/euth_projects/project_detail.html
tests/apps/fakeprojects/phases.py
tests/apps/fakeprojects/views.py
tests/projects/test_mixins.py

* makes phases within timeline clickable
* if a user clicks on a phase, it jumps to the corresponding view

Mkind 2017 07 past phases

---

euth/projects/templates/euth_projects/project_detail.html

Mkind 2017 06 issue 871

---

euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/includes/project_form_information_tab.html
euth/dashboard/templatetags/form_tags.py
euth_wagtail/assets/scss/components/_dashboard.scss

Ah 2017 6 privacy botton

---

euth_wagtail/assets/scss/components/_rating.scss

changed the color of the rating bottons to gray when the rating is not active in the current phase

changed the color of the rating bottons 

---

euth/offlinephases/templates/euth_offlinephases/offlinephase_form.html

change text of link

---

euth/contrib/filters.py
euth/contrib/formset.py
euth/contrib/static/js/formset.js
euth/dashboard/forms.py
euth/dashboard/templates/euth_dashboard/includes/inline_form.html
euth/dashboard/templates/euth_dashboard/includes/project_form_participation_tab.html
euth/flashpoll/views.py
euth/ideas/forms.py
euth/ideas/migrations/0003_idea_category.py
euth/ideas/models.py
euth/ideas/templates/euth_ideas/idea_detail.html
euth/ideas/templates/euth_ideas/idea_form.html
euth/ideas/templates/euth_ideas/idea_list.html
euth/ideas/templates/euth_ideas/includes/idea_list_tile.html
euth/ideas/views.py
euth/organisations/templates/euth_organisations/organisation_list.html
euth_wagtail/assets/scss/all.scss
euth_wagtail/assets/scss/components/_category-form.scss
euth_wagtail/settings/base.py
tests/dashboard/test_dashboard_views.py
tests/ideas/test_idea_views.py

* adding categories to dashboard
* adding categories to proposal
* adding tests

Mkind 2017 07 introducing categories

---

euth/dashboard/forms.py
euth/ideas/forms.py
euth/ideas/views.py
euth/maps/forms.py

* fixing filter issue in ideas by correcting inheritance of categorizableforms
* adding missing queryset for filtering categories in dashboard

Mkind 2017 07 fixing missing categories queryset

---

euth/ideas/templates/euth_ideas/idea_detail.html
euth/ideas/templates/euth_ideas/idea_list.html
euth_wagtail/assets/scss/components/_ideas.scss

fixing issue #901

---

euth/ideas/forms.py
euth/ideas/templates/euth_ideas/idea_form.html
euth_wagtail/assets/scss/components/_category-form.scss

- fix #902 
- fix #904 
- disable category form if no categories are present

Fix remaining category bugs

---

euth/blueprints/blueprints.py
euth/blueprints/names.py
euth/blueprints/templates/euth_blueprints/includes/infopage.html
euth/blueprints/templates/euth_blueprints/result.html
euth/blueprints/templatetags/infopage.py
euth/dashboard/templates/euth_dashboard/blueprint_list.html
euth/documents/phases.py
euth/flashpoll/phases.py
euth/ideas/phases.py
euth/maps/phases.py
euth_wagtail/assets/scss/components/_dashboard.scss
euth_wagtail/assets/scss/core/_type.scss
euth_wagtail/settings/base.py
home/migrations/0027_helppages.py
home/migrations/0028_helppages_example_project.py
home/migrations/0029_add_fields_for_example_projects.py
home/models.py
tests/blueprints/test_algorithm.py

* introducing blueprint infopages 
* introducing blueprints.names

Mkind 2017 08 dst infopage

---

euth/blueprints/templates/euth_blueprints/includes/infopage.html
euth/blueprints/templates/euth_blueprints/result.html
euth/blueprints/templatetags/infopage.py
euth/dashboard/templates/euth_dashboard/blueprint_list.html
euth/documents/phases.py
euth/flashpoll/phases.py
euth/ideas/phases.py
euth/maps/phases.py
euth/offlinephases/phases.py
euth/projects/templates/euth_projects/includes/project_tile.html
euth_wagtail/assets/scss/components/_dashboard.scss
euth_wagtail/assets/scss/core/_type.scss

* wider dst tiles
* adapting phase section in info page
* minor positioning voodoo

improving dst info page 

---

euth/blueprints/blueprints.py
euth/blueprints/forms.py

fixes #918 partly
@slomo I faced problems adding the 'I don't know' option. In code it is there, e.g. [here](https://github.com/liqd/a4-opin/blob/master/euth/blueprints/blueprints.py#L98) but it is not being displayed in the frontend as option. What is the reason for this? I could not figure it out? Is there a problem with having two options with the same value?

change text

---

euth/dashboard/forms.py
euth/flashpoll/services.py

When updating a flashpoll project whithout a change in the phase section, the phases field of objects is empty. Because of that, the send_to_flashpoll function was never called.
So I changed it to use project.phases instead.

Making the poll editable even when it's published.

---

euth/blueprints/templates/euth_blueprints/includes/infopage.html
euth/offlinephases/phases.py
euth_wagtail/assets/scss/components/_dashboard.scss
locale/de/LC_MESSAGES/django.po

* fixing issue #922 
* fixing issue #923 
* fixing issue #924 
* fixing issue #925 
* fixing issue #926

fixing DST issues

---

euth/users/signals.py

fixing avatar upload issue

---

euth/flashpoll/views.py

Hi Yves, Hi Magda,
Just a quick pull request to correct the error 500 raised when accessing a poll when logged out.
Please let me know when it's merged.
Thanks

fixed the error 500 when accessing poll when logged out

---

home/templates/home/manuals_detail_page.html
home/templates/home/manuals_section_page.html

showing translated title 

---

euth/ideas/migrations/0004_change_category_and_image.py
euth/maps/migrations/0005_move_model_change_point_delete_areasettings.py
euth/offlinephases/migrations/0003_change_document_and_text.py
euth/organisations/migrations/0003_change_image_and_logo.py

There were some migrations missing. But this seems strange. Did we alter/delete and such stuff four models?

added migrations

---

euth_wagtail/assets/scss/components/_dashboard.scss

max-width dst tile

---

euth/users/adapters.py
euth/users/templates/euth_users/indicator_menu.html
euth_wagtail/templates/account/email.html
euth_wagtail/templates/account/login.html
euth_wagtail/templates/account/signup.html

fixes the same problem as described here: https://github.com/liqd/a4-advocate-europe/issues/527
I hope, I found them all!

urlencode next parameter

---

euth/ideas/filters.py
euth/ideas/templates/euth_ideas/idea_list.html
euth/ideas/views.py
euth/maps/forms.py
euth/maps/templates/euth_maps/includes/mapidea_list_tile.html
euth/maps/templates/euth_maps/mapidea_list.html
euth/maps/views.py
euth/organisations/templates/euth_organisations/organisation_detail.html
euth/organisations/views.py
euth/projects/filters.py
euth/projects/urls.py
euth/projects/views.py
euth_wagtail/assets/scss/components/_filter_bar.scss
euth_wagtail/assets/scss/components/_orgs.scss
euth_wagtail/assets/scss/components/_pagination.scss
euth_wagtail/assets/scss/components/_projects.scss
euth_wagtail/templates/a4projects/project_list.html
euth_wagtail/urls.py
tests/ideas/test_idea_views.py

Mn 2017 add project list view

---

euth/users/adapters.py
euth/users/templates/euth_users/indicator_menu.html
euth_wagtail/templates/account/login.html
euth_wagtail/templates/account/signup.html

like here: https://github.com/liqd/a4-meinberlin/pull/947

make sure next urls are only encoded once

---

euth_wagtail/assets/scss/components/_dashboard.scss

fixes issue #985

---

euth/contrib/templatetags/contrib_tags.py
euth/organisations/templates/euth_organisations/organisation_list.html
euth_wagtail/templates/a4projects/project_list.html

Mn 2017 11 keep ordering when switching page

---

euth/actions/templates/euth_actions/emails/notify_followers_over_soon.en.email
euth/contrib/filters.py
euth/organisations/filters.py
euth/organisations/views.py
euth/projects/filters.py
euth/projects/views.py
requirements/base.txt

looks hacky to me, is there a better way to achieve this?

Sort countries in country dropdown by the current language's alphabet

---

euth/blueprints/templates/euth_blueprints/includes/infopage.html
euth_wagtail/assets/scss/components/_dashboard.scss

Mkind 2017 11 fixing broken css in modal

---

euth/contrib/templatetags/contrib_tags.py
euth/ideas/templates/euth_ideas/includes/pagination.html
euth/organisations/templates/euth_organisations/organisation_list.html
euth_wagtail/templates/a4projects/project_list.html

* introducing a limited paginator and adapting all `page_range` 
* fixes issue #1005

Introducing a limited paginator, that returns a limited page range.

---

euth_wagtail/assets/scss/wagtail-blocks/_image-text-list-block.scss
home/templates/home/blocks/imageTextBlockList_block.html

Mn 2017 12 fix lineheight

---

euth/contrib/widgets.py
euth/maps/widgets.py
euth/projects/templates/euth_projects/includes/project_tile.html
euth/users/widgets.py
euth_wagtail/settings/production.py

Requires an a4 commit to be merged: https://github.com/liqd/adhocracy4/pull/219

Enable cache busting

---

euth_wagtail/settings/base.py

fix issue # 1061

---

package.json

fix(package): update leaflet to version 1.3.1

---

package.json

fix(package): update flatpickr to version 4.2.4

---

euth/dashboard/static/user_list/react_user_list.jsx

* fixing #1082 
* using jquery's `data()` to retrieve data since jquery tries to cast the data properly.

Mkind 2018 02 issue fixes

---

package.json

fix(package): update file-loader to version 1.1.9

---

package.json

fix(package): update highcharts to version 6.0.7

---

euth_wagtail/templates/a4dashboard/base_dashboard_project.html

add module and project to headings in dashboard

---

home/templates/home/blocks/page_collection_block.html
home/templates/home/manuals_section_page.html
home/templatetags/base_tags.py

Mn 2018 translate header

---

euth/projects/forms.py
euth/projects/templates/euth_projects/dashboard_moderators.html
euth_wagtail/static/scss/components/_dashboard.scss
euth_wagtail/static/scss/components/forms/_general-form.scss
euth_wagtail/templates/a4dashboard/project_create_form.html

this fixes wrong styling of class 'form-hint' and adapts styles from general form styles of OPIN.
fixes #1134, #1130, #1133, #1124, #1125

update styles a bit

---

euth/organisations/templates/euth_organisations/organisation_detail.html

change class name

---

package.json

fix(package): update sass-loader to version 7.0.1

---

euth/contrib/middleware.py
tests/factories.py

had to edit random file for style checks to pass (?)

unique factory usernames and emails

---

Makefile
euth_wagtail/fixtures/site-dev.json

- our emails are @liqd.net now. Less confusing if that's like that everywhere
- in all other projects fixtures are only installed in make fixtures

Ka 2018 05 fixtures

---

package.json
webpack.common.js

Revert "Update dependency webpack to v4"

---

euth_wagtail/templates/base.html

fixes #1201 
@fuzzylogic2000 this is the hotfix from the release branch, I added an issue https://github.com/liqd/a4-opin/issues/1250

hotfix for ckeditor

---

euth_wagtail/static/scss/components/_poll.scss
euth_wagtail/static/scss/components/forms/_questionform.scss
package.json
requirements/base.txt

I forgot this branch had been merged, sorry!

adding styling to results

---

euth_wagtail/templates/socialaccount/connections.html

added correct class name to h3 element fixes#1136

---

euth_wagtail/static/scss/components/_datepicker.scss
euth_wagtail/static/scss/components/forms/_form-control-upload.scss

fixes #1135 
Clicked through site and the reduced margins look good everywhere I checked. 
When there are several margins collected onto 1 section is there a better way to deal with it?

Pm 2018 06 spacing fixes#1135

---

euth/contrib/static/js/app.js

add getCurrentPath to app.js

---

euth_wagtail/templates/a4dashboard/includes/project_list_item.html

remove close button

---

euth_wagtail/static/scss/components/_progress.scss
home/templates/home/manuals_section_page.html

fixes #1423
fixes #1442
fixes #1443

Pm 2019 03 download btn issue

---

euth_wagtail/static/scss/core/_buttons.scss
home/templates/home/manuals_section_page.html

super quick fix to sort alignment issue I missed locally

adding container col div so nested cols match with content nested cols

---

euth/projects/templates/euth_projects/project_detail.html

fixes problem with dropdown js being blocked

top menu dropdown: adding correct filepath for timeline_popover

---

package.json
requirements/base.txt
webpack.common.js

Mn 2019 07 fix add moderators

---

euth_wagtail/assets/js/jquery-fix.js
webpack.common.js

webpack: Properly load jQuery the webpack way

---

euth/maps/widgets.py
webpack.common.js

Was there e reason why we didn't use the a4-map stuff? Do you know, @MagdaN ? Otherwise I will check how alike both are.

apps/maps: fix choose polygon

---

package.json
requirements/base.txt

settings: update a4

---

euth/accounts/forms.py

Analogous to https://github.com/liqd/a4-meinberlin/pull/2890

apps/account/forms: Check username for case insensitive uniqueness

---

.gitignore

Closes https://github.com/liqd/a4-opin/issues/1769

gitignore: Only ignore static folder with dynamic content

---

euth_wagtail/assets/scss/core/_buttons.scss
euth_wagtail/templates/base.html
euth_wagtail/templates/includes/feedback_button.html

Closes https://github.com/liqd/a4-opin/issues/1497

templates: Remove feedback button

---

package.json
requirements/base.txt

update dependencies: update a4 dependency to fix edit async comments

---

package.json
requirements/base.txt

fixes #1851 (actually this time!)

dependency update: update a4 dependency to edit comments take 2

---

euth_wagtail/templates/a4dashboard/base_dashboard_project.html
package.json
requirements/base.txt

…ger reload - not working
@fuzzylogic2000 @rmader at some point I could do with a hand with this but probably not today

a4polls/poll_dashboard: adding id and new a4 hash

---

locale/da/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/djangojs.po
locale/el/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/djangojs.po
locale/ka/LC_MESSAGES/django.po
locale/ka/LC_MESSAGES/djangojs.po
locale/mk/LC_MESSAGES/django.po
locale/mk/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/djangojs.po

These are the new strings, which are also on transifex now.
I think, we should merge even though #1879?!

Ka 2020 05 strings to transifex

---

euth/communitydebate/static/js/fileupload_formset.js
euth_wagtail/assets/js/euth_wagtail.js

Not sure if we do it like this with imports from other js files, but didnt want to just copy the code and have it double then..

Ks 2020 05 communitydebate add event listener to file uploads

---

euth/blueprints/blueprints.py
locale/da/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/djangojs.po
locale/el/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/djangojs.po
locale/ka/LC_MESSAGES/django.po
locale/ka/LC_MESSAGES/djangojs.po
locale/mk/LC_MESSAGES/django.po
locale/mk/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/djangojs.po

Ks 2020 helptext community debate

---

euth/blueprints/blueprints.py
euth/blueprints/static/euth_blueprintsuggest/js/blueprintsuggest.js
euth/blueprints/templates/euth_blueprints/form.html
locale/da/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/djangojs.po
locale/el/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/djangojs.po
locale/ka/LC_MESSAGES/django.po
locale/ka/LC_MESSAGES/djangojs.po
locale/mk/LC_MESSAGES/django.po
locale/mk/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/djangojs.po
webpack.common.js

Ks 2020 07 add blueprintsuggest to webpack

---

locale/da/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/django.po
locale/ka/LC_MESSAGES/django.po
locale/mk/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/django.po

locale: new translations from transifex

---

euth/users/static/users/js/user_search.js
euth_wagtail/assets/scss/components/_commenting-text.scss
euth_wagtail/assets/scss/components/_orgs.scss
euth_wagtail/assets/scss/components/_pagination.scss
euth_wagtail/assets/scss/components/_typeahead.scss
euth_wagtail/templates/a4projects/project_list.html

also quick fix #2008 still little off on ipad but better then before

Pm 2020 09 break word

---

package.json
requirements/base.txt

fixes #2019
see explanation here liqd/adhocracy4/pull/601

update a4 dependency

---

euth/accounts/forms.py
euth/contrib/widgets.py
tests/accounts/test_views.py

the _format_value() method was removed [here](/liqd/a4-opin/commit/52fd55b134185d34b92a36a674dacb25e4e30257#diff-197c914dc8856ba13ee89bc213edbc2f) and as I understood it, we dont need the default date anymore bc of flatpickr? At least it works all fine without..
fixes  #1946

Ks 2020 10 birht date issue fixing

---

euth_wagtail/assets/scss/components/_poll.scss
euth_wagtail/assets/scss/core/_buttons.scss

Adding btn class to style as a link. Adjusting
Poll options to be listed vertically.
Fixes #2106

assets/scss: fixing poll button #2106

---

locale/da/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/djangojs.po
locale/el/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/djangojs.po
locale/ka/LC_MESSAGES/django.po
locale/ka/LC_MESSAGES/djangojs.po
locale/mk/LC_MESSAGES/django.po
locale/mk/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/djangojs.po

New strings as pushed to transifex. Also old (commented out) strings deleted from source files.

locale: makemessages

---

euth_wagtail/assets/scss/components/_user-indicator.scss
euth_wagtail/assets/scss/components/forms/_general-form.scss
euth_wagtail/assets/scss/core/_bootstrap-variables.scss
euth_wagtail/assets/scss/core/_buttons.scss
euth_wagtail/assets/scss/core/_footer.scss

Took the first version of the isntalled bootstrap varoiables file from https://github.com/liqd/a4-opin/commit/906118b9eabfb4e9c7432cf6b5552f80a77f7aec
and compared it to our current variables file

bootstrap: update variables file

---

locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/djangojs.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/djangojs.po
locale/ka/LC_MESSAGES/djangojs.po
locale/mk/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/djangojs.po
package.json
requirements/base.txt

also adds one more string, which I already pushed to transifex

Kl 2021 07 update a4

---

euth_wagtail/settings/base.py

seems to be a remnant of the flashpoll

settings: remove outdated maps key

---

euth/accounts/templates/euth_accounts/profile_form.html
euth_wagtail/assets/scss/components/forms/_general-form.scss

profile/dropdown: arrow to indicate select as dropdown

---

euth/captcha/__init__.py
euth/captcha/apps.py
euth/captcha/assets/captcheck.js
euth/captcha/fields.py
euth/captcha/templates/a4_candy_captcha/captcheck_captcha_widget.html
euth/captcha/widgets.py
euth/contrib/templates/euth_contrib/includes/form_field.html
euth/users/forms.py
euth_wagtail/settings/base.py
euth_wagtail/settings/dev.py
euth_wagtail/templates/account/signup.html

Add captcha to the signup form. Will probably need styling?

Jd 2021 11 signup captcha

---

euth/captcha/__init__.py
euth/captcha/apps.py
euth/captcha/assets/captcheck.js
euth/captcha/fields.py
euth/captcha/templates/a4_candy_captcha/captcheck_captcha_widget.html
euth/captcha/widgets.py
euth/contrib/templates/euth_contrib/includes/form_field.html
euth/users/forms.py
euth_wagtail/settings/base.py
euth_wagtail/settings/dev.py
euth_wagtail/templates/account/signup.html
webpack.common.js

add captcha to registration form

---

requirements/prod.txt

like https://github.com/liqd/a4-meinberlin/pull/3967

deps/python: add hiredis to silence redis-py warnings

---

.tx/config
docs/translations.md
locale/da/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/djangojs.po
locale/el/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/djangojs.po
locale/ka/LC_MESSAGES/django.po
locale/ka/LC_MESSAGES/djangojs.po
locale/mk/LC_MESSAGES/django.po
locale/mk/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/djangojs.po
requirements/dev.txt

* remove deprecated transifex client
* change docs for translation
* update translations

Jd 2022 03 transifex client migration

---

euth/blueprints/blueprints.py

euth/blueprints: updated poll blueprint description

---

euth/communitydebate/filters.py
euth/communitydebate/views.py
euth/ideas/filters.py
euth/ideas/views.py

Fixes https://sentry.liqd.net/organizations/liqd/issues/1957/?project=11 and https://sentry.liqd.net/organizations/liqd/issues/1959/?project=11

Ks 2022 03 fix filter annotations

---

requirements/base.txt

fixes #2358 (with changes in server settings)

deps/py: upgrade to new sentry sdk

---

euth/communitydebate/templates/euth_communitydebate/topic_detail.html
euth/communitydebate/templates/euth_communitydebate/topic_form.html
euth/documents/templates/euth_documents/document_detail.html
euth/documents/templates/euth_documents/document_form.html
euth/documents/templates/euth_documents/paragraph_detail.html
euth/documents/templates/euth_documents/react_paragraphs.html
euth/ideas/templates/euth_ideas/idea_detail.html
euth/ideas/templates/euth_ideas/idea_form.html
euth/maps/templates/euth_maps/mapidea_detail.html
euth/maps/templates/euth_maps/mapidea_list.html
euth/offlinephases/templates/euth_offlinephases/offlineevent_form.html
euth_wagtail/assets/scss/components/forms/_poll-radio.scss
euth_wagtail/assets/scss/core/_containers.scss
euth_wagtail/templates/a4polls/poll_detail.html
home/templates/home/blocks/contact_block.html
requirements/base.txt

project pages were a bit random in their widths so I decided that anything non interactive (list ect.) is medium and anything interactive is narrow now this will help with UX so there's a lot of template stuff

Pm 2022 delete btn

---

euth_wagtail/assets/scss/core/_containers.scss
euth_wagtail/assets/scss/wagtail-blocks/_blocks.scss
home/templates/home/blocks/info_block.html

assets/containers: correct the fixe for image overlap

---

locale/bg/LC_MESSAGES/django.po
locale/bg/LC_MESSAGES/djangojs.po
locale/da/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/djangojs.po
locale/el/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/djangojs.po
locale/ka/LC_MESSAGES/django.po
locale/ka/LC_MESSAGES/djangojs.po
locale/mk/LC_MESSAGES/django.po
locale/mk/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/djangojs.po

US #5530, Task #5530
@Rineee When I pulled, there were only strings from German and Slovenian, is this correct? And there is nothing else that needs to be done here?

locale: translations pulled from transifex

---

docs/translations.md
locale/bg/LC_MESSAGES/django.po
locale/bg/LC_MESSAGES/djangojs.po
locale/da/LC_MESSAGES/django.po
locale/da/LC_MESSAGES/djangojs.po
locale/de/LC_MESSAGES/django.po
locale/de/LC_MESSAGES/djangojs.po
locale/el/LC_MESSAGES/django.po
locale/el/LC_MESSAGES/djangojs.po
locale/en/LC_MESSAGES/django.po
locale/en/LC_MESSAGES/djangojs.po
locale/en_GB/LC_MESSAGES/django.po
locale/en_GB/LC_MESSAGES/djangojs.po
locale/fr/LC_MESSAGES/django.po
locale/fr/LC_MESSAGES/djangojs.po
locale/it/LC_MESSAGES/django.po
locale/it/LC_MESSAGES/djangojs.po
locale/ka/LC_MESSAGES/django.po
locale/ka/LC_MESSAGES/djangojs.po
locale/mk/LC_MESSAGES/django.po
locale/mk/LC_MESSAGES/djangojs.po
locale/sl/LC_MESSAGES/django.po
locale/sl/LC_MESSAGES/djangojs.po
locale/sv/LC_MESSAGES/django.po
locale/sv/LC_MESSAGES/djangojs.po

US #5530
In reference to https://github.com/liqd/a4-opin/pull/2511#issuecomment-1078872588

[#5530] translations: format pulled translations
