- euth/projects/templates/euth_projects/includes/project_tile.html
This removes the hard coded "Liquid democracy e.V." from the bottom of the organisation tile. Currently those tiles are only used on organisation specific pages (e.g. organisations overview or section "other projects of this organisation" in project page). There for I am not sure how much sense this change makes.
> Fix hardcoded organisation name in project tile

- euth/dashboard/apps.py
- euth/dashboard/templates/euth_dashboard/base_dashboard.html
- euth/dashboard/templates/euth_dashboard/dashboard_overview.html
- euth/dashboard/templates/euth_dashboard/profile_detail.html
- euth/dashboard/templatetags/dashboard_templatetags.py
- euth/dashboard/urls.py
- euth/dashboard/views.py
- euth/ideas/templates/euth_ideas/idea_detail.html
- euth/ideas/templates/euth_ideas/includes/idea_list_tile.html
- euth/user_management/apps.py
- euth/user_management/migrations/0003_user_avatar.py
- euth/user_management/models.py
- euth/user_management/signals.py
- euth/user_management/templates/user_management/indicator_menu.html
- euth_wagtail/settings/base.py
- euth_wagtail/static/scss/all.scss
- euth_wagtail/static/scss/components/_dashboard.scss
- euth_wagtail/urls.py
- tests/dashboard/test_dashboard_views.py
- tests/rates/test_rate_models.py
- tests/user_management/test_models.py
This adds a first version of the dashboard, which also contains a profile tab (this might change as a separate profile page is planned). There users can change their avatar. 
@slomo: I added some signals to the user_management models.py. I would have put them in a separate signals.py but I somehow could not use AppConfig within the settings. Maybe you could take a look?
> 2016 08 mn add avatar upload

- euth/comments/api.py
- euth/comments/migrations/0003_auto_20160823_0831.py
- euth/comments/serializers.py
- euth/comments/static/comments/react_comments.js
- euth/rates/api.py
- euth/rates/models.py
- euth/rates/serializers.py
- euth/rates/static/rates/react_rates.js
- euth/rates/templates/rates/react_rates.html
- euth/rates/templatetags/react_rates.py
- tests/comments/conftest.py
- tests/comments/test_api.py
- tests/rates/conftest.py
- tests/rates/test_rate_api.py
- tests/rates/test_rate_models.py
fixes #185 
fixes #178 
PRO
* rate-list and rate-detail api do not accept GET Requests anymore
* creator of rate is not exposed via the rate api
* still uses just one react component
* no extra requests to get the rates
* comment-API ans Rate-API now expose information on rates-count
* comment (for a authenticated user, who hast rated) looks like this:
```
{ 
"id": 38,         
"user_name": "admin",        
"child_comments": [],
"is_deleted": false,
"rates": {
"current_user_rate_id": 65,
"positive_rates": 0,
"negative_rates": 0,
"current_user_rate_value": 0
},
"created": "2016-08-18T08:39:46.342312Z",
"modified": null,
"object_pk": 6,
"comment": "My comment",
"content_type": 50
}
```
* rate detail (for a authenticated user, who hast rated) looks like this
```
{
"id": 66,
"meta_info": { …
```
> 2016 08 mn refactor rates

- euth/contrib/widgets.py
- euth/dashboard/templates/euth_dashboard/profile_detail.html
- euth_wagtail/static/js/euth_wagtail.js
- euth_wagtail/static/scss/components/_forms.scss
> Move upload-wrapper class into widget definition

- euth/organisations/templates/euth_organisations/organisation_detail.html
- euth_wagtail/static/scss/components/_hero-unit.scss
fixes #336 
@vellip I guess the change in _hero-unit.css has been made for a reason. If we put max-width to 60% the whole definition in _hero-unit.css can be deleted
> Mn 2016 10 fix logo stylings

- euth/organisations/templates/euth_organisations/organisation_detail.html
- euth_wagtail/static/scss/components/_accordion-block.scss
- euth_wagtail/static/scss/components/_orgs.scss
Issue:
Organisation Page: kill button "Go To Projects" #415
- deleted the "go to project" button
- adjusted the height of the header image 
- adjusted the accordion 
- social media icons now get a little darker on hover
> Organisation's "Go to project"-button and more

- euth/dashboard/templates/euth_dashboard/includes/project_form_result_tab.html
- euth/dashboard/templates/euth_dashboard/organisation_form.html
- euth_wagtail/assets/scss/components/_action-bar.scss
- euth_wagtail/assets/scss/components/_comments.scss
- euth_wagtail/assets/scss/components/_modal.scss
- euth_wagtail/assets/scss/components/forms/_general-form.scss
- euth_wagtail/assets/scss/core/_bootstrap-variables.scss
- euth_wagtail/assets/scss/core/_buttons.scss
When playing with the project creation form in the dashboard I noticed two accessibility related issues:
- some labels wer not properly associated with their input elements (missing `for` property)
- the input did not indicate the focus
My fix probably changes some styling somewhere. But I do not yet have the overview to estimate the exact effects.
> Improve input focus

- euth/flashpoll/templates/euth_flashpoll/flashpoll_detail.html
Quick fix #550 
Propper solution would be to disable the controls in flashpoll, while still showing results. That will work if the FP admin is there. Until now I just remove the iframe after phase has finished.
> Hide flashpoll iframe if fp phase has finished

- euth_wagtail/templates/base.html
- webpack.config.js
- prevents override of global var  if same library name is used from
different bundles
fixes #687
> Remove clash between adhocracy4 library names

- euth/memberships/models.py
- euth/memberships/templates/emails/invite.en.html
- euth/memberships/templates/euth_memberships/invite_base.html
- euth/memberships/templates/euth_memberships/invite_detail.html
- euth/memberships/templates/euth_memberships/invite_form.html
- euth/memberships/urls.py
- euth/memberships/views.py
- tests/memberships/test_memberships_models.py
- tests/memberships/test_memberships_views.py
- rename old view to update and still require login
- new view doesn't require login and explains the invite first
This is related to some email issue, but also intended to be an overall improvment for the invite flow.
> add a detail view for invites

- euth/dashboard/templates/euth_dashboard/project_list.html
- euth_wagtail/assets/scss/components/_dashboard.scss
- euth_wagtail/assets/scss/components/forms/_general-form.scss
As seen in issue #815 the text `Keine Projekte erstellt` is ugly positioned. This PR fixes this.
> fixing issue that the filter result text is ugly positioned

- euth/contrib/static/js/dateTimeInput.js
- euth/contrib/widgets.py
- euth/dashboard/forms.py
- euth/dashboard/static/add_offline_phase/add_offline_phase.js
- euth/dashboard/templates/euth_dashboard/includes/project_form_participation_tab.html
- package.json
The language/date display switching seems to work now.
Not yet working: 
- showing form field for start and end dates when creating offline phases
- adding a timezone display with the current timezone to the datepicker (or helptext of the form)
> Ka 2017 05 user timezone datepicker

- euth/ideas/templates/euth_ideas/idea_list.html
This is needed because a list could be empty, because everything is filtered out. In that case I want to show the filters so users can unapply them.
> Show filters and sorts even for empty lists

- home/templates/home/includes/sf_blocks.html
- home/templates/home/manuals_detail_page.html
- home/templates/home/manuals_index.html
- home/templates/home/simple_page.html
fixes #1003 
I guess after the automated update of wagtail in https://github.com/liqd/a4-opin/commit/13c35be122eaa4f73c54e62587fb9114a15867fa using block.value for block rendering was not valid anymore (switching back to older version also did not work for some migrations errors, but I also did not try too hard)
@slomo this should be merged with the release2.8 branch and not master, right?
> change block.value to block when rendering blocks

- euth/organisations/views.py
- required because sorting and filtering translated attributes will
otherwise produce one result per translation
> Set translation before filters in org list

- euth_wagtail/settings/base.py
django failed to read statics from `static/bundles`. added the corresponding dir to config.
> reading statics from bundles dir

- package.json
- webpack.common.js
* removing copy-webpack-plugin as this is not used anymore
* obsoletes #1047
> removing unused dependency

- euth_wagtail/settings/build.py
- euth_wagtail/settings/production.py
As cache busting does not work in this project, we decided to disable it for now. We will try to use it again, when the django version is updated-
> remove ManifestStaticFilesStorage from build.py and production.py

- euth_wagtail/settings/production.py
They are not used anymore, as the django-compressor dependency
has been removed
>  Remove COMPRESS* settings

- euth/ideas/views.py
- euth/organisations/templates/euth_organisations/organisation_form.html
- euth_wagtail/static/scss/components/_dashboard-nav.scss
- euth_wagtail/static/scss/components/_dashboard.scss
- euth_wagtail/static/scss/core/_buttons.scss
- euth_wagtail/templates/a4dashboard/base_dashboard_project.html
- euth_wagtail/templates/a4dashboard/base_project_list.html
- euth_wagtail/templates/a4dashboard/blueprint_list.html
- euth_wagtail/templates/a4dashboard/includes/project_list_item.html
- euth_wagtail/templates/a4dashboard/project_list.html
- change heading of orgsnisation settings
- link to project detail view in project list
- move button 'new project'
- make blueprint list narrower and change styling of heading
- hover-styles gray-btn
- add link back to project list (but I am unhappy with what it looks like!)
> Ka 2019 02 dashboard styling

- euth/projects/static/euth_projects/timeline-popover.js
- euth/projects/templates/euth_projects/project_detail.html
this stops popover js overwriting dropdown and ensures both work when on same page
> dropdown and popovers: adding js for dropdowns in popover file

- euth/dashboard/forms.py
- euth/dashboard/static/language_switch/react_language_switch.jsx
- euth/organisations/templates/euth_organisations/organisation_form.html
- tests/dashboard/test_dashboard_views.py
There are long explanations in the commits. Please read them separately.
> Ka 2020 04 translate org fields

- euth/ideas/templates/euth_ideas/includes/pagination.html
- euth/ideas/templatetags/idea_tags.py
- tests/ideas/test_templatetags.py
This makes sure we e.g. keep the selected ordering scheme. Copied from A+.
Fixes #1406
---
Can be tested on https://opin-dev.liqd.net/en/projects/paging-test/
> euth/ideas/templates: Include all existing GET parameters in pagination

- euth/projects/templates/euth_projects/project_detail.html
sorry I thought I checked for file name but obviously not, why did it work locally though?!
> Pm 2020 05 popover removal

- Makefile
@Rineee 
So, the migrations problem was that the migrations were not run in a normal test, which kind of makes sense to run test-clean every time there where migrations. But as we handle that differently in all other projects, I also changed it here.
And the test-clean target was probably just broken because it coudln't find the image.
Now it still takes veeery long to run the tests, but they are not failing and can be run with py.test as well (which also takes forever). :tada:
> makefile/settings: adapt test targets to other projects

- requirements/base.txt
I think this should fix this error by django-autoslug:
`AssertionErrorautoslug.fields in pre_save
errorslug is defined before trying to ensure uniqueness`
Sentry: https://sentry.liqd.net/sentry/opin-prod/issues/1047/
Solution: https://stackoverflow.com/questions/40919070/django-autoslug-error-slug-is-defined-before-trying-to-ensure-uniqueness
> deps/python: add package needed by django-autoslug for cyrillic fields

- euth/communitydebate/views.py
- tests/communitydebate/test_communitydebate_views.py
fixes https://sentry.liqd.net/sentry/opin-prod/issues/1198/events/
I think we have contradictory linters now? When trying to commit, I got:
`/home/katharinaschmid/a4-opin/euth/documents/static/documents/Paragraph.jsx`
`119:19  error  Expected indentation of 20 space characters but found 18  react/jsx-indent-props`
So I changed that and then got:
`/home/katharinaschmid/a4-opin/euth/documents/static/documents/Paragraph.jsx`
`119:1  error  Expected indentation of 18 spaces but found 20  indent`
> communitydebate/views: initialize upload forms when form is not valid

- euth/contrib/sitemaps/adhocracy4_sitemap.py
- euth/projects/templates/euth_projects/includes/project_hero_unit.html
- euth/projects/templatetags/project_class_tags.py
- euth_wagtail/templates/a4dashboard/includes/project_basic_form.html
- package.json
- requirements/base.txt
- tests/apps/fakeprojects/models.py
- tests/communitydebate/test_communitydebate_views.py
- tests/dashboard/test_dashboard_views.py
- tests/documents/test_document_views.py
- tests/ideas/test_idea_views.py
- tests/memberships/test_memberships_views.py
The first commit only fixes the py code in so far that the tests succeed and the views are alright. 
But we still need to think about what to do with the access enum. If we need to use all three, we also need to make sure the semipublic makes sense for the projects. And I think as the enum can't be overwritten, we have to use all three (or finally change from enum to choices, which is too late now).
Also, the js code is currently broken. :grimacing:
> deps: update a4 and adapt py code to access enum

- euth/memberships/dashboard.py
- euth/memberships/templates/euth_memberships/emails/invite.en.email
- euth/projects/apps.py
- euth/projects/overwrites.py
- euth/projects/templates/euth_projects/includes/project_hero_unit.html
- euth/projects/templates/euth_projects/includes/project_list_item.html
- euth/projects/templates/euth_projects/includes/project_tile.html
- euth/projects/templates/euth_projects/project_detail.html
- euth_wagtail/assets/scss/components/_forms.scss
- euth_wagtail/assets/scss/components/forms/_widget-radioselect.scss
- euth_wagtail/templates/a4dashboard/includes/project_list_item.html
I wanted to add some styling for the radio buttons of the choices of project access in basic settings of project, but didnt succeed..
I wanted to add something like:
`.widget-radioselect {
ul {
list-style: none;
margin: 0;
padding: 0;
}
}
`
but didnt really know where to put it, so its used.. can you help me with that @fuzzylogic2000 or @khamui ?
Also, the helptext for access is now gone, because we removed it in A4, but I guess it is alright, because the choices are self-explanatory?
Open question: probably people should also be able to apply for membership in semi-public projects, right? Maybe we can discuss where to put that tomorrow @fuzzylogic2000 ?
> Ks 2021 04 make semi public projects work

- euth_wagtail/settings/base.py
- requirements/base.txt
This wasn't too bad. And it is fine on a fresh DB.
But I did not have a lot of wagtail in my local not-fresh DB. Could you also test it on yours @phillimorland @Rineee ? I will also add more wagtail to my unupdated DB and check it out more thoroughly after lunch.
> deps/python: update wagtail to 2.11 lts

- euth_wagtail/assets/scss/core/_type.scss
closes #2316 
think setting all `<a>`-elements to no underline is better.
> general styles: setting all opin anchor elements '<a>' to not underlined

- euth_wagtail/templates/micawber/video.html
- home/templates/home/blocks/video_block.html
close #2340 
@hello-kathi I couldn't check the issue on Prod ("not showing yt videos at all"). Because I am not an admin there.
This PR just fixes the sizing of the embedded videos.
> embeds: using bs5 classes for embeds

- euth/dashboard/static/user_list/react_user_list.jsx
not sure where to ask this, but I just saw in this file we use jQuery. Do we want to get rid of it here at some point? Shall I create an issue or even a task in our technical backlog?
Another thing that I saw is how the Userlist is getting "injected" via template tags. I am not totally sure what it does or how it works. Maybe a refactor here could reduce complexity as well?
see:
https://github.com/liqd/a4-opin/blob/d4cd69a053765105292bad545e89be43027012ea/euth/dashboard/static/user_list/react_user_list.jsx#L113
> dashboard/moderators: queryselecting input checkboxes fixed

- euth/contrib/admin.py
> euth/contrib: overwrite module django admin to redirect to project

- requirements/base.txt
psycopg2-binary shouldn't be used in production
> replace psycopg2-binary with psycopg2

- euth/users/adapters.py
- euth/users/templates/euth_users/indicator_menu.html
- euth_wagtail/settings/base.py
- euth_wagtail/templates/account/login.html
- euth_wagtail/templates/account/signup_closed.html
- tests/users/test_views.py
testing instructions:
https://taiga.liqd.net/project/liqd-liquid-software/us/7942?milestone=386
for google signin with new google account need to check once we merge to dev. But with the signup disabled in the `euth/users/adapter.py` it should not allow new google singups
> [7942] disable registration
